language: php

matrix:
  include:
    - php: hhvm-3.18
      sudo: required
      group: edge
    - php: 7.1
    - php: 7.2
    - php: 7.3

  fast_finish: true

cache:
    directories:
        - vendor/bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_VERSION=5.7
    - SYMFONY_DEPRECATIONS_HELPER=99999

before_script:
    - |
      export COMPOSER_UP='composer update --dev --no-interaction --no-progress --no-suggest --ansi'

    - |
      if [[ $deps = low ]]; then
          $COMPOSER_UP --prefer-lowest --prefer-stable
      else
          $COMPOSER_UP
      fi

branches:
  only:
    - master

script:
    - ./vendor/bin/simple-phpunit
